"""empty message

Revision ID: d27f6f702ffd
Revises: cdb6cee29ccf
Create Date: 2018-12-04 17:00:41.307523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd27f6f702ffd'
down_revision = 'cdb6cee29ccf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_user', sa.Column('image', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('t_user', 'image')
    # ### end Alembic commands ###
